### ISSUE TITLE
Not compatible with Composer

### ISSUE THREAD

**Issue by deviationist** [shipsaas/laravel-jwks#1]
You need to add it to packagist.org and add at least one release (tag). As of now one has to add the repo to composer.json and specifically use the main-branch. Or maybe it is not release ready yet?

**Comment by sethsandaru** [comment]
@deviationist hey man, yeah indeed.

I'm finalizing the implementation (unit testing) & prepare the documentation before releasing this. Will tag you soon on this.

Additionally, feel free to give this a star or "watch" this repo for further updates :D

**Comment by sethsandaru** [comment]
hey @deviationist , v1.0.0 is released, enjoy!
